### ISSUE TITLE
'__bitwise' macro redefined [-Wmacro-redefined]

### ISSUE THREAD

**Issue by sajid15feb** [tinyalsa/tinyalsa#118]
Hi , 

I am trying to build project using android studio but its giving me error 

**'__bitwise' macro redefined [-Wmacro-redefined]** 

Please check below logs for same 

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:externalNativeBuildDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.UncheckedException: Build command failed.
Error while executing process G:\software\dev\mobile\android-sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\Dev\TS2.0\ALSA\TinyalsaTest\app\.externalNativeBuild\cmake\debug\x86_64 --target tinymix}
[1/5] Building C object CMakeFiles/tinyalsa.dir/src/pcm.c.o
[2/5] Building C object CMakeFiles/tinyalsa.dir/src/mixer.c.o
FAILED: G:\software\dev\mobile\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe  --target=x86_64-none-linux-android --gcc-toolchain=G:/software/dev/mobile/android-sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/windows-x86_64 --sysroot=G:/software/dev/mobile/android-sdk/ndk-bundle/sysroot  -I../../../../include -isystem G:/software/dev/mobile/android-sdk/ndk-bundle/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC   -Wall -Wextra -Werror -Wfatal-errors -MD -MT CMakeFiles/tinyalsa.dir/src/pcm.c.o -MF CMakeFiles\tinyalsa.dir\src\pcm.c.o.d -o CMakeFiles/tinyalsa.dir/src/pcm.c.o   -c D:\Dev\TS2.0\ALSA\TinyalsaTest\app\src\pcm.c
D:\Dev\TS2.0\ALSA\TinyalsaTest\app\src\pcm.c:46:9: fatal error: '__bitwise' macro redefined [-Wmacro-redefined]
#define __bitwise
        ^
G:/software/dev/mobile/android-sdk/ndk-bundle/sysroot/usr/include\linux/types.h:25:9: note: previous definition is here
#define __bitwise __bitwise__
        ^
1 error generated.
ninja: build stopped: subcommand failed.

	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
Caused by: Build command failed.
Error while executing process G:\software\dev\mobile\android-sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\Dev\TS2.0\ALSA\TinyalsaTest\app\.externalNativeBuild\cmake\debug\x86_64 --target tinymix}
[1/5] Building C object CMakeFiles/tinyalsa.dir/src/pcm.c.o
[2/5] Building C object CMakeFiles/tinyalsa.dir/src/mixer.c.o
FAILED: G:\software\dev\mobile\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe  --target=x86_64-none-linux-android --gcc-toolchain=G:/software/dev/mobile/android-sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/windows-x86_64 --sysroot=G:/software/dev/mobile/android-sdk/ndk-bundle/sysroot  -I../../../../include -isystem G:/software/dev/mobile/android-sdk/ndk-bundle/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC   -Wall -Wextra -Werror -Wfatal-errors -MD -MT CMakeFiles/tinyalsa.dir/src/pcm.c.o -MF CMakeFiles\tinyalsa.dir\src\pcm.c.o.d -o CMakeFiles/tinyalsa.dir/src/pcm.c.o   -c D:\Dev\TS2.0\ALSA\TinyalsaTest\app\src\pcm.c
D:\Dev\TS2.0\ALSA\TinyalsaTest\app\src\pcm.c:46:9: fatal error: '__bitwise' macro redefined [-Wmacro-redefined]
#define __bitwise
        ^
G:/software/dev/mobile/android-sdk/ndk-bundle/sysroot/usr/include\linux/types.h:25:9: note: previous definition is here
#define __bitwise __bitwise__
        ^
1 error generated.
ninja: build stopped: subcommand failed.

	at com.android.build.gradle.tasks.ExternalNativeBuildTaskUtils.executeBuildProcessAndLogError(ExternalNativeBuildTaskUtils.java:244)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:307)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 44 more

![tinyalsa_macro_redefined](https://user-images.githubusercontent.com/3103247/45617664-a9b3f400-ba90-11e8-8fd3-81cea047e09d.PNG)

**Comment by tay10r** [comment]
So from the looks of it, you're building with Android Studio on Windows. I don't have Android Studio installed, so it may take me a bit to reproduce this error and fix it.

**Comment by tay10r** [comment]
@sajid15feb This should be fixed with recent commits. I tested compiling on Android with clang. Let me know if it is fixed for you. I'll leave this issue open for a bit so you have time to check.
